title: Carter is Smarter
subtitle: Annoying People With No Sense of Humor

name: Steve Carter

url: https://blog.sdcarter.com
repository: sdcarter/blog.sdcarter.com
read_time: true
search: true

email: steve@sdcarter.com
description: > 
  Annoying People With No Sense of Humor

twitter_username: SteveCarter
github_username:  sdcarter
linkedin_username: cartersd

remote_theme: "mmistakes/minimal-mistakes"
google_analytics: UA-102665323-2

minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# home page specific details
show_excerpts: true
