title: Carter is Smarter
author: Steve Carter
email: steve@sdcarter.com
description: > 
  Annoying People With No Sense of Humor

twitter_username: SteveCarter
github_username:  sdcarter
linkedin_username: cartersd

theme: minima
google_analytics: UA-102665323-2

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - about.md
#  - "[www](https://www.sdcarter.com)"
#  - [blog](https://blog.sdcarter.com)
#  - [wiki](https://wiki.sdcarter.com)

# home page specific details
show_excerpts: true
